sudo: required
services:
  - docker

before_install:
  - docker build -t jessemellinger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jessemellinger/docker-react npm run test -- --coverage